name: Continuous Test

on:
  # When someone create a pull request from the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: Run tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test # will run `yarn test` command

